### ISSUE TITLE
Unable to build a remote vllm distribution with inline milvus provider on a mac

### ISSUE THREAD

**Issue by hemajv** [meta-llama/llama-stack#1716]
I'm trying to build a remote vllm distribution with milvus as the inline vector db provider on a Mac, however I run into errors. 

### System Info

```
OS: macOS 15.3.2 (arm64)
Python version: 3.10.5
Python platform: macOS-15.3.2-arm64-arm-64bit
CPU: Apple M1 Pro
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### 🐛 Describe the bug

This is my `build.yaml`:
```
name: vllm-milvus
version: '2'
distribution_spec:
  description: Use (an external) vLLM server for running LLM inference with milvus
  providers:
    inference:
    - remote::vllm
    - inline::sentence-transformers
    vector_io:
    - inline::milvus
    safety:
    - inline::llama-guard
    agents:
    - inline::meta-reference
    eval:
    - inline::meta-reference
    datasetio:
    - remote::huggingface
    - inline::localfs
    scoring:
    - inline::basic
    - inline::llm-as-judge
    - inline::braintrust
    telemetry:
    - inline::meta-reference
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::code-interpreter
    - inline::rag-runtime
    - remote::model-context-protocol
    - remote::wolfram-alpha
image_type: container
```

This is how I'm building the distribution:

```
$ git clone https://github.com/meta-llama/llama-stack.git
$ cd llama-stack

# Create the venv to install llamastack locally
$ python -m venv .stack
$ source .stack/bin/activate
$ pip install -U .

# Build with build.yaml
$ export LLAMA_STACK_DIR="."
$ export USE_COPY_NOT_MOUNT="true"
$ export CONTAINER_BINARY=podman
$ llama stack build --config build.yaml --image-type container --image-name vllm-remote-milvus
```

### Error logs

```
 > [ 5/11] RUN uv pip install --no-cache scipy tqdm matplotlib redis pymongo blobfile aiosqlite pillow numpy pymilvus requests pandas datasets psycopg2-binary autoevals transformers opentelemetry-sdk pypdf nltk scikit-learn opentelemetry-exporter-otlp-proto-http mcp tree_sitter chardet sentencepiece openai aiosqlite fastapi fire httpx uvicorn:
143.5       -I/usr/local/include/python3.10 -c polyleven.c -o
143.5       build/temp.linux-aarch64-cpython-310/polyleven.o
143.5 
143.5       [stderr]
143.5       error: command 'gcc' failed: No such file or directory
143.5 
143.5       hint: This usually indicates a problem with the package or the build
143.5       environment.
143.5   help: `polyleven` (v0.9.0) was included because `autoevals` (v0.0.124)
143.5         depends on `polyleven`
------
Containerfile:8
--------------------
   6 |     ENV UV_SYSTEM_PYTHON=1
   7 |     RUN pip install uv
   8 | >>> RUN uv pip install --no-cache scipy tqdm matplotlib redis pymongo blobfile aiosqlite pillow numpy pymilvus requests pandas datasets psycopg2-binary autoevals transformers opentelemetry-sdk pypdf nltk scikit-learn opentelemetry-exporter-otlp-proto-http mcp tree_sitter chardet sentencepiece openai aiosqlite fastapi fire httpx uvicorn
   9 |     RUN uv pip install --no-cache sentence-transformers --no-deps
  10 |     RUN uv pip install --no-cache torch torchvision --index-url https://download.pytorch.org/whl/cpu
--------------------
ERROR: failed to solve: process "/bin/sh -c uv pip install --no-cache scipy tqdm matplotlib redis pymongo blobfile aiosqlite pillow numpy pymilvus requests pandas datasets psycopg2-binary autoevals transformers opentelemetry-sdk pypdf nltk scikit-learn opentelemetry-exporter-otlp-proto-http mcp tree_sitter chardet sentencepiece openai aiosqlite fastapi fire httpx uvicorn" did not complete successfully: exit code: 1
```

### Expected behavior

Expect the build to succeed
