### ISSUE TITLE
`agents: out of token budget` message and no output when running ReAct example

### ISSUE THREAD

**Issue by MichaelClifford** [meta-llama/llama-stack#1783]
### System Info

* llama stack server: llamastack/distribution-remote-vllm:0.1.8
* model: meta-llama/Llama-3.2-3B-Instruct
* python client: llama-stack-client 0.1.8
* vllm server: docker.io/vllm/vllm-openai:v0.7.3'

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I'm seeing no chat or tool output and the following message in my llama stack server logs when using `llamastack/distribution-remote-vllm:0.1.8` and running the react_agent example (https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/react_agent.py) with meta-llama/Llama-3.2-3B-Instruct.

`llama_stack.providers.inline.agents.meta_reference.agent_instance:604 agents: out of
token budget, exiting.` 

I have confirmed that I am in fact not running out of tokens and can see in the vllm server logs that it correctly returns a chat completion `"POST /v1/chat/completions HTTP/1.1" 200 OK` 

I noticed that it looks like `stop_reason` will get set to "out_of_tokens" if no other reason is provided. Not sure if this could be causing the issue or not. https://github.com/meta-llama/llama-stack/blob/ba14552a32f3a6cb49714234e2cd8a3258168891/llama_stack/providers/inline/agents/meta_reference/agent_instance.py#L567 

additional context: the same example code and model work as expected when using the ollama model server via `llamastack/distribution-ollama:0.1.7`

### Error logs

```
`llama_stack.providers.inline.agents.meta_reference.agent_instance:604 agents: out of
token budget, exiting.` 
```

### Expected behavior

 [ReAct Agent Example](https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/react_agent.py) works as expected with remote vllm. 

Thanks!

**Comment by wukaixingxp** [comment]
The default [max_token is only 4096](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/templates/vllm-gpu/run.yaml#L19), maybe increase it to 8196 will solve this issue, you can set it by 
```
docker run \
  -it \
  --pull always \
  -p $LLAMA_STACK_PORT:$LLAMA_STACK_PORT \
  -v ./run.yaml:/root/my-run.yaml \
  llamastack/distribution-remote-vllm \
  --yaml-config /root/my-run.yaml \
  --port $LLAMA_STACK_PORT \
  --env INFERENCE_MODEL=$INFERENCE_MODEL \
  --env VLLM_URL=http://host.docker.internal:$INFERENCE_PORT/v1 \
  --env MAX_TOKENS=8196
```
see more doc [here](https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/remote-vllm.html#running-llama-stack).

**Comment by wukaixingxp** [comment]
@MichaelClifford  BTW.. vllm tool_call requires some additional parameters like 
```
CUDA_VISIBLE_DEVICES=0 vllm serve meta-llama/Llama-3.2-11B-Vision-Instruct --enforce-eager --max-num-seqs 16 --tensor_parallel_size 1  --max_model_len 8196 --enable-auto-tool-choice --tool-call-parser llama3_json --chat-template tool_call_3_2.jinja
```
Please refer to [this document](https://docs.vllm.ai/en/latest/features/tool_calling.html) for more details.

**Comment by MichaelClifford** [comment]
Thanks for the response @wukaixingxp 😃 

I increase `VLLM_MAX_TOKENS` in my llama stack server and I already had these set `--enable-auto-tool-choice --tool-call-parser llama3_json --chat-template tool_call_3_2.jinja` in vllm. But went ahead and set the other parameters you suggested as well and re-ran the [react_agent example](https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/react_agent.py). Unfortunately, did not fix the issue.  

Heres the vllm config:
```yaml
          image: 'vllm/vllm-openai:v0.7.3'
          args:
            - '--model'
            - meta-llama/Llama-3.2-3B-Instruct
            - '--enable-auto-tool-choice'
            - '--chat-template'
            - /app/tool_chat_template_llama3.2_json.jinja
            - '--tool-call-parser'
            - llama3_json
            - '--port'
            - '8000'
            - '--enforce-eager'
            - '--max-num-seqs'
            - '16'
            - '--tensor_parallel_size'
            - '1'
            - '--max_model_len'
            - '8196'
```

Is there another way in which tokens are being counted or limited per requests? maybe `--max-num-batched-tokens`?
