### ISSUE TITLE
Missing Models when running llama-stack from main branch

### ISSUE THREAD

**Issue by Bobbins228** [meta-llama/llama-stack#1816]
### System Info

OS: Linux
Llama Stack version: main branch
Llama Stack Python Client ver: 0.1.8
Ollama ver: 0.6.2

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

This is how I have configured my current setup for testing Llama Stack from the main branch

Setup conda environment
```
yes | conda create -n llama-stack python=3.10
conda activate llama-stack
```

Install Llama-Stack project
`pip install -e .`
`pip install -r requirements.txt`

```
pip freeze | grep llama
-e git+ssh://git@github.com/meta-llama/llama-stack.git@81393afb350e14435449eb8568b753534a0eca85#egg=llama_stack
llama_stack_client==0.1.8
```

Build and Run Llama-Stack Server

```
llama stack build --config llama_stack/templ
ates/ollama/build.yaml
```

Export necessary args
```
export INFERENCE_MODEL="meta-llama/Llama-3.2-3B-Instruct"
export LLAMA_STACK_PORT=8321
```

```
llama stack run /home/mark/.llama/distributi
ons/llama-stack3/llama-stack3-run.yaml
```

Run the [rag_with_vector_db.py script](https://github.com/meta-llama/llama-stack-apps/blob/592a101c155082125d8f1170cf4824860a0fd921/examples/agents/rag_with_vector_db.py#L1)

`python rag_with_vector_db.py`

Output
```
No available models. Exiting.
```

output of `ollama list models`
```
NAME                         ID              SIZE      MODIFIED    
all-minilm:latest            1b226e2802db    45 MB     2 hours ago    
llama3.2:3b-instruct-fp16    195a8c01d91e    6.4 GB    2 days ago 
```

output of `llama-stack-client models list`
```""```
I successfully registered the `meta-llama/Llama-3.2-3B-Instruct` model but I get errors when I try to register the `all-MiniLM-L6-
v2` model.

`llama-stack-client models register "all-MiniLM-L6-
v2" --provider-model-id "all-minilm:latest"`

```
╭─────────────────────────────────────────────────────────────────────────────────╮
│ Failed to register model                                                        │
│                                                                                 │
│ Error Type: BadRequestError                                                     │
│ Details: Error code: 400 - {'detail': "Invalid value: Model 'all-minilm:latest' │
│ is not available in Ollama. Available models: llama3.2:3b-instruct-fp16"}       │
╰─────────────────────────────────────────────────────────────────────────────────╯
```

### Error logs

```
╭─────────────────────────────────────────────────────────────────────────────────╮
│ Failed to register model                                                        │
│                                                                                 │
│ Error Type: BadRequestError                                                     │
│ Details: Error code: 400 - {'detail': "Invalid value: Model 'all-minilm:latest' │
│ is not available in Ollama. Available models: llama3.2:3b-instruct-fp16"}       │
╰─────────────────────────────────────────────────────────────────────────────────╯
```

### Expected behavior

Successfully registered model all-minilm:latest

**Comment by Bobbins228** [comment]
@mattf 
I made some discoveries today on this topic it turns out when I build a run file it is missing the models and tool groups. 
`uv run llama stack build --config llama_stack/templates/ollama/build.yaml --image-name llama-stack --image-type venv`
<details>
  <summary>llama-stack-run.yaml</summary>

  ```
  version: '2'
  image_name: llama-stack-mark
  container_image: null
  apis:
  - inference
  - vector_io
  - safety
  - agents
  - telemetry
  - eval
  - datasetio
  - scoring
  - tool_runtime
  providers:
    inference:
    - provider_id: ollama
      provider_type: remote::ollama
      config:
        url: ${env.OLLAMA_URL:http://localhost:11434}
    vector_io:
    - provider_id: sqlite-vec
      provider_type: inline::sqlite-vec
      config:
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/llama-stack-mark}/sqlite_vec.db
    safety:
    - provider_id: llama-guard
      provider_type: inline::llama-guard
      config:
        excluded_categories: []
    agents:
    - provider_id: meta-reference
      provider_type: inline::meta-reference
      config:
        persistence_store:
          type: sqlite
          namespace: null
          db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/llama-stack-mark}/agents_store.db
    telemetry:
    - provider_id: meta-reference
      provider_type: inline::meta-reference
      config:
        service_name: "${env.OTEL_SERVICE_NAME:\u200B}"
        sinks: ${env.TELEMETRY_SINKS:console,sqlite}
        sqlite_db_path: ${env.SQLITE_DB_PATH:~/.llama/distributions/llama-stack-mark/trace_store.db}
    eval:
    - provider_id: meta-reference
      provider_type: inline::meta-reference
      config:
        kvstore:
          type: sqlite
          namespace: null
          db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/llama-stack-mark}/meta_reference_eval.db
    datasetio:
    - provider_id: huggingface-0
      provider_type: remote::huggingface
      config:
        kvstore:
          type: sqlite
          namespace: null
          db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/llama-stack-mark}/huggingface_datasetio.db
    - provider_id: localfs-1
      provider_type: inline::localfs
      config:
        kvstore:
          type: sqlite
          namespace: null
          db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/llama-stack-mark}/localfs_datasetio.db
    scoring:
    - provider_id: basic-0
      provider_type: inline::basic
      config: {}
    - provider_id: llm-as-judge-1
      provider_type: inline::llm-as-judge
      config: {}
    - provider_id: braintrust-2
      provider_type: inline::braintrust
      config:
        openai_api_key: ${env.OPENAI_API_KEY:}
    tool_runtime:
    - provider_id: brave-search-0
      provider_type: remote::brave-search
      config:
        api_key: ${env.BRAVE_SEARCH_API_KEY:}
        max_results: 3
    - provider_id: tavily-search-1
      provider_type: remote::tavily-search
      config:
        api_key: ${env.TAVILY_SEARCH_API_KEY:}
        max_results: 3
    - provider_id: code-interpreter-2
      provider_type: inline::code-interpreter
      config: {}
    - provider_id: rag-runtime-3
      provider_type: inline::rag-runtime
      config: {}
    - provider_id: model-context-protocol-4
      provider_type: remote::model-context-protocol
      config: {}
    - provider_id: wolfram-alpha-5
      provider_type: remote::wolfram-alpha
      config:
        api_key: ${env.WOLFRAM_ALPHA_API_KEY:}
  metadata_store: null
  models: [] # Missing Inference model and all-MiniLM-L6-v2
  shields: []
  vector_dbs: []
  datasets: []
  scoring_fns: []
  benchmarks: []
  tool_groups: [] # Missing tools specified in tool_runtime
  logging: null
  server:
    port: 8321
    tls_certfile: null
    tls_keyfile: null
    auth: null
  ```
</details> 

I was able to add them manually based on what I saw in [run.yaml](https://github.com/meta-llama/llama-stack/blob/main/llama_stack/templates/ollama/run.yaml) in the ollama templates but I would assume that the models and tool groups would automatically be populated when running `llama stack build`.

In doing the above everything works as expected.
