### ISSUE TITLE
Adding TLS Support for vector_io Milvus

### ISSUE THREAD

**Issue by divyaruhil** [meta-llama/llama-stack#2010]
### 🚀 Describe the new functionality needed

Currently, if we try to connect the Llama stack server to a remote Milvus instance that has TLS enabled, the connection fails because TLS support is not implemented in the Llama stack codebase. As a result, users are unable to use secured Milvus deployments out of the box.

### 💡 Why is this needed? What if we don't build it?

if TLS disabled :-
```
vector_io:
  - provider_id: milvus
    provider_type: remote::milvus
    config:
      uri: "http://<host>:<port>"
      token: "<user>:<password>"
```

if TLS enabled :-
```
vector_io:
  - provider_id: milvus
    provider_type: remote::milvus
    config:
      uri: "http://<host>:<port>"
      token: "<user>:<password>"
      secure: True
      server_pem_path: "path/to/server.pem"
```
