### ISSUE TITLE
Unable to list models when using OpenAI and Gemini inference providers

### ISSUE THREAD

**Issue by rchaganti** [meta-llama/llama-stack#2115]
### System Info

My system is a simple desktop with no GPU as I intend to use OpenAI and Gemini inference backends.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Here is the build.yaml I used to build a custom distro.
```yaml
version: '2'
distribution_spec:
  name: 'ga2025-lstack'
  description: 'GA 2025 LStack'
  providers:
    inference:
    - remote::openai
    - remote::gemini
    vector_io:
    - remote::chromadb
    - remote::pgvector
    - inline::faiss
    safety:
    - inline::llama-guard
    scoring:
    - inline::basic
    eval:
    - inline::meta-reference
    datasetio:
    - inline::localfs
    agents:
    - inline::meta-reference
    tool_runtime:
    - inline::rag-runtime
    - remote::model-context-protocol
    - remote::tavily-search
    telemetry:
    - inline::meta-reference
image_type: container
```

Here is the run.yaml
```yaml
version: '2'
image_name: 2025-lstack
container_image: 2025-lstack
apis:
- inference
- vector_io
- safety
- scoring
- eval
- datasetio
- agents
- tool_runtime
- telemetry
providers:
  inference:
  - provider_id: openai-0
    provider_type: remote::openai
    config:
      api_key: ${env.OPENAI_API_KEY}
  - provider_id: gemini-1
    provider_type: remote::gemini
    config:
      api_key: ${env.GEMINI_API_KEY}
  vector_io:
  - provider_id: faiss-2
    provider_type: inline::faiss
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/ga2025-lstack}/faiss_store.db
  safety:
  - provider_id: llama-guard
    provider_type: inline::llama-guard
    config:
      excluded_categories: []
  scoring:
  - provider_id: basic
    provider_type: inline::basic
    config: {}
  eval:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/ga2025-lstack}/meta_reference_eval.db
  datasetio:
  - provider_id: localfs
    provider_type: inline::localfs
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/ga2025-lstack}/localfs_datasetio.db
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/ga2025-lstack}/agents_store.db
  tool_runtime:
  - provider_id: rag-runtime-0
    provider_type: inline::rag-runtime
    config: {}
  - provider_id: model-context-protocol-1
    provider_type: remote::model-context-protocol
    config: {}
  - provider_id: tavily-search-2
    provider_type: remote::tavily-search
    config:
      api_key: ${env.TAVILY_SEARCH_API_KEY:}
      max_results: 3
  telemetry:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      service_name: ${env.OTEL_SERVICE_NAME:}
      sinks: ${env.TELEMETRY_SINKS:console,sqlite}
      sqlite_db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/ga2025-lstack}/trace_store.db
metadata_store: null
models:
- metadata: {}
  model_id: openai-gpt-4
  provider_id: openai-0
  model_type: llm
- metadata: {}
  model_id: gemini-2.0-flash
  provider_id: gemini-1
  model_type: llm
shields: []
vector_dbs: []
datasets: []
scoring_fns: []
benchmarks: []
tool_groups: []
logging: null
server:
  port: 8321
  tls_certfile: null
  tls_keyfile: null
  auth: null
  disable_ipv6: false
external_providers_dir: null
```

I am able to run llama stack server. However, the following command does not return anything.

```sh
llama-stack-client models list
```

The following command results in an error:
```sh
$ llama-stack-client inference chat-completion --message "What is a Llama?"
╭─────────────────────────────────────╮
│ Failed to inference chat-completion │
│                                     │
│ Error Type: IndexError              │
│ Details: list index out of range    │
╰─────────────────────────────────────╯

$ llama-stack-client inference chat-completion --model-id gemini-2.0-flash --message "What is a Llama?"
╭────────────────────────────────────────────────────────────────────────────────────────────╮
│ Failed to inference chat-completion                                                        │
│                                                                                            │
│ Error Type: BadRequestError                                                                │
│ Details: Error code: 400 - {'detail': "Invalid value: Model 'gemini-2.0-flash' not found"} │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

### Error logs

This is what I see in the llama stack server logs

```sh
INFO:     172.17.0.1:48428 - "GET /v1/models HTTP/1.1" 200 OK
08:43:25.535 [START] /v1/models
08:43:25.545 [END] /v1/models [StatusCode.OK] (10.29ms)
INFO:     172.17.0.1:39594 - "GET /v1/models HTTP/1.1" 200 OK
08:48:51.147 [START] /v1/models
08:48:51.158 [END] /v1/models [StatusCode.OK] (10.91ms)
INFO:     172.17.0.1:50188 - "GET /v1/models HTTP/1.1" 200 OK
08:50:06.947 [START] /v1/models
08:50:06.956 [END] /v1/models [StatusCode.OK] (8.89ms)
08:50:36.746 [START] /v1/inference/chat-completion
ERROR    2025-05-08 08:50:36,745 __main__:208 server: Error executing endpoint route='/v1/inference/chat-completion'
         method='post'
         ╭───────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮
         │ /usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py:206 in endpoint           │
         │                                                                                                             │
         │   203 │   │   │   │   │   return StreamingResponse(gen, media_type="text/event-stream")                     │
         │   204 │   │   │   │   else:                                                                                 │
         │   205 │   │   │   │   │   value = func(**kwargs)                                                            │
         │ ❱ 206 │   │   │   │   │   return await maybe_await(value)                                                   │
         │   207 │   │   │   except Exception as e:                                                                    │
         │   208 │   │   │   │   logger.exception(f"Error executing endpoint {route=} {method=}")                      │
         │   209 │   │   │   │   raise translate_exception(e) from e                                                   │
         │                                                                                                             │
         │ /usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py:163 in maybe_await        │
         │                                                                                                             │
         │   160                                                                                                       │
         │   161 async def maybe_await(value):                                                                         │
         │   162 │   if inspect.iscoroutine(value):                                                                    │
         │ ❱ 163 │   │   return await value                                                                            │
         │   164 │   return value                                                                                      │
         │   165                                                                                                       │
         │   166                                                                                                       │
         │                                                                                                             │
         │ /usr/local/lib/python3.10/site-packages/llama_stack/providers/utils/telemetry/trace_protocol.py:103 in      │
         │ async_wrapper                                                                                               │
         │                                                                                                             │
         │   100 │   │   │                                                                                             │
         │   101 │   │   │   with tracing.span(f"{class_name}.{method_name}", span_attributes) as span:                │
         │   102 │   │   │   │   try:                                                                                  │
         │ ❱ 103 │   │   │   │   │   result = await method(self, *args, **kwargs)                                      │
         │   104 │   │   │   │   │   span.set_attribute("output", serialize_value(result))                             │
         │   105 │   │   │   │   │   return result                                                                     │
         │   106 │   │   │   │   except Exception as e:                                                                │
         │                                                                                                             │
         │ /usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py:260 in chat_completion  │
         │                                                                                                             │
         │   257 │   │   )                                                                                             │
         │   258 │   │   if sampling_params is None:                                                                   │
         │   259 │   │   │   sampling_params = SamplingParams()                                                        │
         │ ❱ 260 │   │   model = await self.routing_table.get_model(model_id)                                          │
         │   261 │   │   if model is None:                                                                             │
         │   262 │   │   │   raise ValueError(f"Model '{model_id}' not found")                                         │
         │   263 │   │   if model.model_type == ModelType.embedding:                                                   │
         │                                                                                                             │
         │ /usr/local/lib/python3.10/site-packages/llama_stack/providers/utils/telemetry/trace_protocol.py:103 in      │
         │ async_wrapper                                                                                               │
         │                                                                                                             │
         │   100 │   │   │                                                                                             │
         │   101 │   │   │   with tracing.span(f"{class_name}.{method_name}", span_attributes) as span:                │
         │   102 │   │   │   │   try:                                                                                  │
         │ ❱ 103 │   │   │   │   │   result = await method(self, *args, **kwargs)                                      │
         │   104 │   │   │   │   │   span.set_attribute("output", serialize_value(result))                             │
         │   105 │   │   │   │   │   return result                                                                     │
         │   106 │   │   │   │   except Exception as e:                                                                │
         │                                                                                                             │
         │ /usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py:274 in get_model │
         │                                                                                                             │
         │   271 │   async def get_model(self, model_id: str) -> Model:                                                │
         │   272 │   │   model = await self.get_object_by_identifier("model", model_id)                                │
         │   273 │   │   if model is None:                                                                             │
         │ ❱ 274 │   │   │   raise ValueError(f"Model '{model_id}' not found")                                         │
         │   275 │   │   return model                                                                                  │
         │   276 │                                                                                                     │
         │   277 │   async def register_model(                                                                         │
         ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
         ValueError: Model 'gemini-2.0-flash' not found
INFO:     172.17.0.1:41756 - "POST /v1/inference/chat-completion HTTP/1.1" 400 Bad Request
```

### Expected behavior

The model list must be returned and the inference should work.
