### ISSUE TITLE
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).

### ISSUE THREAD

**Issue by Rohan-Jalil** [meta-llama/llama-stack#248]
### Command:

**llama stack run Llama3.2-11B-Vision-Instruct --port 5000**

**Output:**

```
Using config `/Users/mac/.llama/builds/conda/Llama3.2-11B-Vision-Instruct-run.yaml`
Resolved 4 providers
 inner-inference => meta-reference
 models => __routing_table__
 inference => __autorouted__
 inspect => __builtin__

[2024-10-15 07:20:46,247] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Loading model `Llama3.2-11B-Vision-Instruct`
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of (1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, 50714) cannot be retrieved (gai error: 8 - nodename nor servname provided, or not known).
```

**config `/Users/mac/.llama/builds/conda/Llama3.2-11B-Vision-Instruct-run.yaml**

```
version: '2'
built_at: '2024-10-15T06:25:20.837875'
image_name: Llama3.2-11B-Vision-Instruct
docker_image: null
conda_env: Llama3.2-11B-Vision-Instruct
logging:
  level: DEBUG
  file:
    enabled: true
    path: /Users/mac/llama-32.log
authentication:
  enabled: false
apis:
- inference
providers:
  inference:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      model: Llama3.2-11B-Vision-Instruct
      torch_seed: null
      max_seq_len: 4096
      max_batch_size: 1
```

### Command:

python -m llama_stack.apis.inference.client localhost 5000 --no-auth

### Output

User>hello world, write me a 2 sentence poem about the moon

**Error: HTTP 403**
