### ISSUE TITLE
Standardize errors for "unsupported model".

### ISSUE THREAD

**Issue by RohanAwhad** [meta-llama/llama-stack#2517]
### 🚀 Describe the new functionality needed

Currently, there are 2 different error messages for reporting unsupported models by remote inference providers.
1. Just has a simple `ValueError: Unsupported model: non-existent-model`
2. The other is more descriptive, and mentions supported list of models:
    ```
    ValueError: Model 'non-existent-model' is not supported. Supported models are: 
    meta-llama/Llama-3.1-8B-Instruct, meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo,
    Llama3.1-8B-Instruct, meta-llama/Llama-3.1-70B-Instruct, 
    meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo, Llama3.1-70B-Instruct, 
    meta-llama/Llama-3.1-405B-Instruct-FP8, 
    meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo, Llama3.1-405B-Instruct, 
    meta-llama/Llama-3.2-3B-Instruct, meta-llama/Llama-3.2-3B-Instruct-Turbo, 
    Llama3.2-3B-Instruct, meta-llama/Llama-3.2-11B-Vision-Instruct, 
    meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo, Llama3.2-11B-Vision-Instruct, 
    [...]
    ```

We should standardize this. And I as a consumer of this would prefer the later, as I don't have to guess or lookup something else to figure out the list of supported models.

Providers which show error 1:
- OpenAI
- Anthropic
- Gemini
- Groq
- SambaNova

Providers which show error 2:
- Ollama (the wording for this is different but it lists available model)
- Watsonx
- Cerebras
- Together
- Fireworks

### 💡 Why is this needed? What if we don't build it?

It is a great developer experience.

### Other thoughts

Parent Issue: #2379 

#### Error Message 1:

You can create a new `test_run_openai.yaml` and paste the following config in it:

```yaml
version: '2'
image_name: test-image
apis:
- inference
providers:
  inference:
  - provider_id: openai
    provider_type: remote::openai
    config:
      max_tokens: 8192
models:
- metadata: {}
  model_id: "non-existent-model"
  provider_id: openai
  model_type: llm
server:
  port: 8321
```

And run the server with:
```bash
uv run llama stack run test_run_openai.yaml
```

#### Error Message 2:

You can create a new `test_run_together.yaml` and paste the following config in it:

```yaml
version: '2'
image_name: test-image
apis:
- inference
providers:
  inference:
  - provider_id: together
    provider_type: remote::together
    config:
      max_tokens: 8192
models:
- metadata: {}
  model_id: "non-existent-model"
  provider_id: together
  model_type: llm
server:
  port: 8321
```

And run the server with:
```bash
uv run llama stack run test_run_together.yaml
```
