### ISSUE TITLE
option without agents database

### ISSUE THREAD

**Issue by nikolaydubina** [meta-llama/llama-stack#252]
I would like to make server without agents nor database functions. but now it is impossible since images are shipped with either sqlite, redis, postresql

```
Configuring API `agents`...
> Configuring provider `(meta-reference)`
Enter `type` for persistence_store (options: redis, sqlite, postgres) (default: sqlite): 
```

**Comment by yanxi0830** [comment]
You may skip building agents with the following build config `inference-no-agents.yaml`
```yaml
name: local-no-agent
distribution_spec:
  description: inference only
  docker_image: null
  providers:
    inference: meta-reference
image_type: docker
```

Then, run `llama stack build --config inference-no-agents.yaml`
