### ISSUE TITLE
auto routed apis should not be required in apis_to_serve

### ISSUE THREAD

**Issue by yanxi0830** [meta-llama/llama-stack#297]
we currently enforce all auto routed apis be required to in apis_to_serve, we should allow apis_to_serve in run.yaml to be source of truth. 

E.g. this should not be required if you don't need datasets API
```
apis:
...
- datasets
- datasetio
providers:
  datasetio:
  - provider_id: meta0
    provider_type: meta-reference
```

https://github.com/meta-llama/llama-stack/blob/21f2e9adf59b7cf7535ba9312006af97a5b14e3b/llama_stack/distribution/resolver.py#L70
