### ISSUE TITLE
Create the distribution of AMD ROCm GPU

### ISSUE THREAD

**Issue by alexhegit** [meta-llama/llama-stack#341]
### 🚀 The feature, motivation and pitch

Create the distribution of AMD ROCm GPU like the distributions/meta-reference-gpu which is base on NVIDIA GPU.

**Comment by alexhegit** [comment]
Here is my compose.yaml for creating the AMD ROCm GPU distribution. 
```
services:
  llamastack:
    image: rocm/pytorch 
    network_mode: "host"
    volumes:
      - ~/.llama:/root/.llama
      - ./run.yaml:/root/my-run.yaml
    ports:
      - "5000:5000"
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    environment:
      - HIP_VISIBLE_DEVICES=0
    command: []
    entrypoint: bash -c "python -m llama_stack.distribution.server.server --yaml_config /root/my-run.yaml"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
```

And I do 'docker compose up' with it and got failed log as bellow.

```
$ docker compose up
[+] Running 2/1
 ✔ Container meta-reference-gpu-rocm-llamastack-1                        Created                                                                                                           0.4s 
 ! llamastack Published ports are discarded when using host network mode                                                                                                                   0.0s 
Attaching to llamastack-1
llamastack-1  | /opt/conda/envs/py_3.10/bin/python: Error while finding module specification for 'llama_stack.distribution.server.server' (ModuleNotFoundError: No module named 'llama_stack')
llamastack-1 exited with code 0
```

Any help to fix it?
