### ISSUE TITLE
Memory insert error

### ISSUE THREAD

**Issue by heyjustinai** [meta-llama/llama-stack#454]
### System Info

llama_stack               0.0.52
llama_stack_client        0.0.49   

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Whenever I try to run memory_banks.register

```
    client.memory_banks.register(
        memory_bank={
            "identifier": bank_id,
            "embedding_model": "all-MiniLM-L6-v2",
            "chunk_size_in_tokens": 512,
            "overlap_size_in_tokens": 64,
            "provider_id": "remote::chromadb",
        }
    )
   
```

or inserting into memory bank

```     client.memory.insert(bank_id=bank_id, documents=documents)

```
I am getting this meta-reference-0 error whenever I try to call memory insert or memory_bank register

```
INFO:     ::1:54384 - "POST /memory_banks/register HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 244, in endpoint
    return await maybe_await(value)
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 204, in maybe_await
    return await value
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routers.py", line 44, in insert_documents
    return await self.routing_table.get_provider_impl(bank_id).insert_documents(
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 148, in get_provider_impl
    return self.impls_by_provider_id[obj.provider_id]
KeyError: 'meta-reference-0'
INFO:     ::1:54384 - "POST /memory/insert HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 244, in endpoint
    return await maybe_await(value)
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 204, in maybe_await
    return await value
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routers.py", line 44, in insert_documents
    return await self.routing_table.get_provider_impl(bank_id).insert_documents(
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 148, in get_provider_impl
    return self.impls_by_provider_id[obj.provider_id]
KeyError: 'meta-reference-0'

```

### Error logs
my yaml

```
version: '2'
built_at: '2024-11-09T16:52:49.941955'
image_name: meta-reference-gpu
docker_image: null
conda_env: meta-reference-gpu
apis:
- inference
- memory
- safety
- agents
- telemetry
providers:
  inference:
  - provider_id: meta-reference-0
    provider_type: meta-reference
    config:
      model: Llama3.2-11B-Vision-Instruct
      torch_seed: null
      max_seq_len: 4096
      max_batch_size: 1
      create_distributed_process_group: true
      checkpoint_dir: null
  - provider_id: meta-reference-1
    provider_type: meta-reference
    config:
      model: Llama3.1-8B-Instruct
      torch_seed: null
      max_seq_len: 4096
      max_batch_size: 1
      create_distributed_process_group: true
      checkpoint_dir: null
  memory:
  - provider_id: remote::chromadb
    provider_type: remote::chromadb
    config:
      host: localhost
      port: 6000
  # - provider_id: faiss-0
  #   provider_type: faiss
  #   config:
  #     kvstore:
  #       namespace: null
  #       type: sqlite
  #       db_path: /home/justinai/.llama/runtime/faiss_store.db
  safety:
  - provider_id: meta-reference-0
    provider_type: meta-reference
    config:
      llama_guard_shield: null
      enable_prompt_guard: false
  agents:
  - provider_id: meta-reference-0
    provider_type: meta-reference
    config:
      persistence_store:
        namespace: null
        type: sqlite
        db_path: /home/justinai/.llama/runtime/kvstore.db
  telemetry:
  - provider_id: meta-reference-0
    provider_type: meta-reference
    config: {}
metadata_store: null

```

Error 
```
llama stack run /home/justinai/.llama/distributions/llamastack-meta-reference-gpu/meta-reference-gpu-run.yaml
Resolved 13 providers
 inner-inference => meta-reference-0
 inner-inference => meta-reference-1
 inner-memory => remote::chromadb
 models => __routing_table__
 inference => __autorouted__
 inner-safety => meta-reference-0
 shields => __routing_table__
 safety => __autorouted__
 memory_banks => __routing_table__
 memory => __autorouted__
 agents => meta-reference-0
 telemetry => meta-reference-0
 inspect => __builtin__

Loading model `Llama3.2-11B-Vision-Instruct`
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/home/justinai/.conda/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
Loaded in 6.39 seconds
[rank0]:[W1113 20:36:56.314926116 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
NCCL version 2.21.5+cuda12.4
Loaded model...
Loading model `Llama3.1-8B-Instruct`
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/home/justinai/.conda/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
Loaded in 5.30 seconds
[rank0]:[W1113 20:37:04.179931980 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
NCCL version 2.21.5+cuda12.4
Loaded model...
Initializing ChromaMemoryAdapter with url: http://localhost:6000
Connecting to Chroma server at: localhost:6000
/home/justinai/.conda/envs/llamastack-meta-reference-gpu/lib/python3.10/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_id" in Body_endpoint_models_register_post has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Serving API models
 GET /models/get
 GET /models/list
 POST /models/register
Serving API shields
 GET /shields/get
 GET /shields/list
 POST /shields/register
Serving API memory_banks
 GET /memory_banks/get
 GET /memory_banks/list
 POST /memory_banks/register
Serving API safety
 POST /safety/run_shield
Serving API inspect
 GET /health
 GET /providers/list
 GET /routes/list
Serving API telemetry
 GET /telemetry/get_trace
 POST /telemetry/log_event
Serving API agents
 POST /agents/create
 POST /agents/session/create
 POST /agents/turn/create
 POST /agents/delete
 POST /agents/session/delete
 POST /agents/session/get
 POST /agents/step/get
 POST /agents/turn/get
Serving API inference
 POST /inference/chat_completion
 POST /inference/completion
 POST /inference/embeddings
Serving API memory
 POST /memory/insert
 POST /memory/query

Listening on ['::', '0.0.0.0']:5000
INFO:     Started server process [422840]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://['::', '0.0.0.0']:5000 (Press CTRL+C to quit)
`rag_agent_docs` already registered with `faiss-0`
INFO:     ::1:62098 - "POST /memory_banks/register HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 244, in endpoint
    return await maybe_await(value)
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 204, in maybe_await
    return await value
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routers.py", line 44, in insert_documents
    return await self.routing_table.get_provider_impl(bank_id).insert_documents(
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 148, in get_provider_impl
    return self.impls_by_provider_id[obj.provider_id]
KeyError: 'meta-reference-0'
INFO:     ::1:62098 - "POST /memory/insert HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 244, in endpoint
    return await maybe_await(value)
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 204, in maybe_await
    return await value
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routers.py", line 44, in insert_documents
    return await self.routing_table.get_provider_impl(bank_id).insert_documents(
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 148, in get_provider_impl
    return self.impls_by_provider_id[obj.provider_id]
KeyError: 'meta-reference-0'
INFO:     ::1:62098 - "POST /memory/insert HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 244, in endpoint
    return await maybe_await(value)
  File "/data/users/justinai/llama-stack/llama_stack/distribution/server/server.py", line 204, in maybe_await
    return await value
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routers.py", line 44, in insert_documents
    return await self.routing_table.get_provider_impl(bank_id).insert_documents(
  File "/data/users/justinai/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 148, in get_provider_impl
    return self.impls_by_provider_id[obj.provider_id]
KeyError: 'meta-reference-0'
INFO:     ::1:62098 - "POST /memory/insert HTTP/1.1" 500 Internal Server Error
```

### Expected behavior

Being able to call `client.memory.insert` and `client.memory_banks.register` without errors.
