### ISSUE TITLE
[Adding new Inference provider] get error at runtime when the stack code is looking for a model to serve

### ISSUE THREAD

**Issue by sanjayk-github-dev** [meta-llama/llama-stack#460]
### System Info

PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.0.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: version 3.30.2
Libc version: N/A

Python version: 3.10.15 (main, Oct  3 2024, 02:24:49) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.1
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I'm adding a new remote Inference Provider. I essentially copied the code for remote vLLM, since the new provider supports OpenAI compatible api. 

I have added model aliases in the new adapter as below:

```
model_aliases = [
    build_model_alias(
        "llama-3.1-8b-instant",
        CoreModelId.llama3_1_8b_instruct.value,
    ),
    build_model_alias(
        "llama-guard-3-8b",
        CoreModelId.llama_guard_3_8b.value,
    ),
]

```

However at runtime, I'm getting the following error:

`ValueError: Model `Llama3.1-8B-Instruct` not served by provider: `remote::groq-0`. Make sure there is an Inference provider serving this model.`

**Is there any addition step required to register the models?**

### Error logs

```
Traceback (most recent call last):
  File "/Users/xxx/Workspace/llama-stack/llama_stack/distribution/server/server.py", line 212, in sse_generator
    async for item in event_gen:
  File "/Users/xxx/Workspace/llama-stack/llama_stack/providers/inline/agents/meta_reference/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/Users/xxx/Workspace/llama-stack/llama_stack/providers/inline/agents/meta_reference/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/Users/xxx/Workspace/llama-stack/llama_stack/providers/inline/agents/meta_reference/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/Users/xxx/Workspace/llama-stack/llama_stack/providers/inline/agents/meta_reference/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
  File "/Users/xxx/Workspace/llama-stack/llama_stack/distribution/routers/routers.py", line 119, in chat_completion
    provider = self.routing_table.get_provider_impl(model_id)
  File "/Users/xxx/Workspace/llama-stack/llama_stack/distribution/routers/routing_tables.py", line 132, in get_provider_impl
    raise ValueError(
ValueError: Model `Llama3.1-8B-Instruct` not served by provider: `remote::groq-0`. Make sure there is an Inference provider serving this model.
```

### Expected behavior

No error.

**Comment by dineshyv** [comment]
Thanks for reporting this issue. We have made some backend schema/ data model/ registration changes as part of which auto discovery of provider's models has been removed. We are thinking of right way to bring this functionality back but in the mean time you can add the models that the distribution can serve in run.yaml's model config key.

**Comment by mattf** [comment]
@sanjayk-github-dev directly adding the model in run.yaml works for me. you likely need -

```
...
metadata_store: null
models:
  - model_id: Llama3.1-8B-Instruct
    provider_id: remote::groq-0
shields: []
...
```

**Comment by sanjayk-github-dev** [comment]
Thanks, that did the trick!

On a different note, how do I specify the `shields` in the `run.yaml` file? The example code is looking for `llama_guard` but I'm not sure how to configure that in the `run.yaml` file.

Thanks!

**Comment by cheesecake100201** [comment]
```
shields:
- params: null
  shield_id: meta-llama/Llama-Guard-3-8B
  provider_id: null
  provider_shield_id: null
  ```
  
  Add this just after models in your run.yaml file, should work after that
  @sanjayk-github-dev

**Comment by sanjayk-github-dev** [comment]
@cheesecake100201 - I get the following error after adding the above. 

`ValueError: Unknown model: `meta-llama/Meta-Llama-Guard-3-8B``

**Comment by cheesecake100201** [comment]
Can you check which model groq has like the names it uses?

**Comment by sanjayk-github-dev** [comment]
Grow has `Llama-Guard-3-8B`. Should I use grow as provider instead?

**Comment by cheesecake100201** [comment]
For you use case, groq has this model
`llama-guard-3-8b`
Visit this link and check these models with there names and try it out.
https://console.groq.com/docs/api-reference#models-list

**Comment by sanjayk-github-dev** [comment]
Here's my working `run.yaml` file (without `shields` definitions). Please advise how I should modify it for `shields`. Thanks!

```
version: '2'
built_at: '2024-11-14T15:19:55.963596'
image_name: groq-stack
docker_image: null
conda_env: groq-stack
apis:
- inference
- safety
- agents
- memory
- datasetio
- scoring
- eval
- telemetry
providers:
  inference:
  - provider_id: remote::groq-0
    provider_type: remote::groq
    config:
      url: https://api.groq.com/openai/v1
      api_token: <api-token>
  safety:
  - provider_id: meta0
    provider_type: inline::llama-guard
    config:
      model: Llama-Guard-3-1B
      excluded_categories: []
  agents:
  - provider_id: inline::meta-reference-0
    provider_type: inline::meta-reference
    config:
      persistence_store:
        namespace: null
        type: sqlite
        db_path: /Users/xxx/.llama/runtime/kvstore.db
  memory:
  - provider_id: remote::chromadb-0
    provider_type: remote::chromadb
    config:
      host: localhost
      port: 8000
      protocol: http
  datasetio:
  - provider_id: inline::localfs-0
    provider_type: inline::localfs
    config: {}
  scoring:
  - provider_id: inline::basic-0
    provider_type: inline::basic
    config: {}
  eval:
  - provider_id: inline::meta-reference-0
    provider_type: inline::meta-reference
    config:
      kvstore:
        namespace: null
        type: sqlite
        db_path: /Users/xxx/.llama/runtime/meta_reference_eval.db
  telemetry:
  - provider_id: inline::meta-reference-0
    provider_type: inline::meta-reference
    config: {}
metadata_store: null
models:
  - model_id: ${env.LLAMA_INFERENCE_MODEL:Llama3.1-8B-Instruct}
    provider_id: remote::groq-0
  - model_id: ${env.LLAMA_SAFETY_MODEL:Llama-Guard-3-8B}
    provider_id: remote::groq-0
shields: []
memory_banks: []
datasets: []
scoring_fns: []
eval_tasks: []
```

**Comment by cheesecake100201** [comment]
Can you help me with understanding why you are using env.LLAMA_REFERENCE_MODEL in models, I would suggest take a look at the inference implementation of together inference, and its run.yaml in the templates directory. It should give you a good idea as to how you would want to proceed. For a bit clarity in models you need another key called as provider_model_id where you would store the name of model you get from groq. Model_id is something which I am assuming is you give the name to it.

**Comment by sanjayk-github-dev** [comment]
@cheesecake100201 - I can certainly remove env.LLAMA_REFERENCE_MODEL but that's not the issue. My models are working as expected. The `provider_model_id` is not needed since the Inference code is building the proper aliases.

My current issue is getting the [Hello example](https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/hello.py) to work when safety (shield) is enabled.

**Comment by yanxi0830** [comment]
> My current issue is getting the [Hello example](https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/hello.py) to work when safety (shield) is enabled.

Could you share the latest error? For getting safety(shield) to work. Wondering if you have shields set? You can check via `llama-stack-client shields list`. You will also need to add this in your run.yaml id to specify the shield_id. 

```
shields:
- params: null
  shield_id: ${env.LLAMA_SAFETY_MODEL}
  provider_id: null
  provider_shield_id: null
```
